project/project/urls.py
from django.contrib import admin
from django.urls import include, path
admin.autodiscover()

urlpatterns = [
    path('', include('psa.urls')),
    path('admin/', admin.site.urls),
]

project/psa/urls.py
from django.urls import path

from psa import views

app_name = 'psa'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('provsvar/<int:pk>/', views.ProvsvarDetail.as_view(), name='provsvar_detail'),
    path('patient/<int:pk>/', views.PatientDetail.as_view(), name='patient_detail'),
    path('add_provsvar/', views.ProvsvarCreateView.as_view(), name='add_provsvar'),
    path('add_patient/', views.PatientCreateView.as_view(), name='add_patient'),
    path('hantera/<int:pk>/', views.HanteraDetail.as_view(), name='hantera_detail'),
]

project/sample/urls.py
from django.urls import path

from . import views

app_name = 'sample'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

project/psa/models.py
from django.db import models
from django.urls import reverse
import sqlite3

from datetime import datetime, timedelta
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here.

def read_from_db(value):
	x = str(value)
	con = sqlite3.connect('db.sqlite3')
	cur = con.cursor()
	cur.execute("SELECT 1 FROM psa_patient where ssn = ?", (x,))
	y = cur.fetchall()
	if y:
		pass
	else:
		raise ValidationError(_('%(value)s personnummer saknas i databasen'), params={'value': value},)


def validate_ssn(value):
	x = str(value)
	if len(x) is not 10:
		raise ValidationError(_('%(value)s är inte ett giltigt personnummer. Ange tio siffror utan streck..'), params={'value': value},)

def validate_postnr(value):
	if value <= 10000 or value >= 99999:
		raise ValidationError(_('%(value)s är inte en giltig postkod. Ange en giltig postkod 5 siffror utan mellanrum.'), params={'value': value},)

class Patient(models.Model):
	ssn = models.BigIntegerField(validators=[validate_ssn],primary_key=True, unique=True)
	namn = models.CharField(max_length=100)
	gata = models.CharField(max_length=50)
	postort = models.CharField(max_length=50)
	postnr = models.IntegerField(validators=[validate_postnr])
	mail = models.EmailField(max_length=50)
	operationsdatum = models.DateField()
	created = models.DateField(auto_now_add=True)
	kallelsedatum = models.DateField()
	
	class Meta:
		verbose_name_plural = "Patienter"

	def __str__(self):
		return self.namn

	def save(self, *args, **kwargs):
		self.kallelsedatum = self.operationsdatum + timedelta(days=180)
		super().save(*args, **kwargs)  # Call the "real" save() method.

class Provsvar(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	result = models.DecimalField(max_digits=5, decimal_places=2)
	done = models.CharField(max_length=100, default='False')
	ssn = models.ForeignKey(Patient, default='None', verbose_name="Kopplad patient", on_delete=models.SET_DEFAULT, validators=[validate_ssn, read_from_db])
	
	def __str__(self):
		return str(self.created)
	
	class Meta:
		verbose_name_plural = "Provsvar"

class Hantera(models.Model):
	ssn = models.BigIntegerField(validators=[validate_ssn],primary_key=True, unique=True)
	name = models.CharField(max_length=150)
	result = models.CharField(max_length=150)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = "Hantera"

project/psa/templates/psa/forms.py
# from django import forms
# from django.forms import ModelForm

# from .models import *

# class ProvsvarForm(forms.ModelForm):

#     class Meta:
#         model = Provsvar
#         fields = '__all__'

project/psa/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.urls import reverse_lazy

from .models import Provsvar, Patient, Hantera

# def index(request):
#     pass

# def detail(request):
#     pass


class IndexView(generic.ListView):
    template_name = 'psa/index.html'
    context_object_name = 'latest_provsvar_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'latest_provsvar_list': Provsvar.objects.order_by('-created')[:10],
            'patient_list': Patient.objects.order_by('-created'),
            'hantera_list': Hantera.objects.order_by('-ssn'),
        })
        return context

    def get_queryset(self):
        return Patient.objects.all(), Hantera.objects.all()

class ProvsvarDetail(generic.DetailView):
    model = Provsvar
    template_name = 'psa/detail.html'

class PatientDetail(generic.DetailView):
    model = Patient
    template_name = 'psa/patient.html'

class HanteraDetail(generic.DeleteView):
    model = Hantera
    success_url = '/'
    template_name = 'psa/hantera.html'
    

class ProvsvarCreateView(generic.CreateView):
    model = Provsvar
    fields = ['ssn', 'result']
    template_name = 'psa/add_provsvar.html'
    success_url = '../'
    # success_message = "%(ssn)s was created successfully"

class PatientCreateView(generic.CreateView):
    model = Patient
    fields = ['ssn', 'namn','gata','postort', 'postnr', 'mail','operationsdatum']
    template_name = 'psa/add_patient.html'
    success_url = '../'
    # success_message = "%(ssn)s was created successfully"

project/sample/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Sample

def index(request):
    pass

def detail(request):
    pass

class IndexView(generic.ListView):
    template_name = 'sample/index.html'
    context_object_name = 'latest_sample_list'

    def get_queryset(self):
        """Return the last ten published samples."""
        return Sample.objects.order_by('-created')[:10]

class DetailView(generic.DetailView):
    model = Sample
    template_name = 'sample/detail.html'

project/psa/templates/psa/add_patient.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center-column{
		width:800px;
		margin: 20px auto;
		padding:20px;
		background-color: rgb(248, 185, 143);
		border-radius: 20px;
		box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

</style>

<div class="center-column">

    <div class="box">
        <div class = "form">
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info" type="submit">Lägg till</button>
        </div>
    </form>
    </div>
</div>

project/psa/templates/psa/add_provsvar.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center-column{
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%, -100%);
	padding: 10px;
	text-align: center;
	width:500px;
	margin: 20px auto;
	padding:20px;
	background-color: rgb(248, 185, 143);
	border-radius: 20px;
	box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

</style>

<div class="center-column">

    <div class="box">
        <div class = "form">
        <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info" type="submit">SUBMIT</button>
        </div>
    </form>
    </div>
</div>

project/psa/templates/psa/detail.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center-column{
		width:500px;
		margin: 20px auto;
		padding:20px;
		background-color: rgb(248, 185, 143);
		border-radius: 20px;
		box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

</style>

<div class="center-column">

  {% block content %}
    <h3>Patient: {{ provsvar.ssn }}</h3>
    Registrerat:  {{ provsvar.created }}
    Resultat:  {{ provsvar.result }}
  {% endblock %}

</div>

project/psa/templates/psa/hantera.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center {
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%, -150%);
	padding: 10px;
	text-align: center;
	width:500px;
	margin: 20px auto;
	padding:20px;
	background-color: rgb(248, 185, 143);
	border-radius: 20px;
	box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

</style>


	<div class="center">
	<form method="post">{% csrf_token %}
		<p>Är du säker på att du vill ta bort "{{ object }}"?</p>
		<input type="submit" value="Ok">
	</form>
	</div>

project/psa/templates/psa/index.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center-column{
		width:95%;
        height: 95%;
        height: auto;
		margin: 20px auto;
		padding:25px;
		background-color: rgb(248, 185, 143);
		border-radius: 20px;
		box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

    .btn-info{
		margin: 5px auto;
        padding:10px;
    }
    
    .col-sm{
        text-align: center;
    }
    .row-sm{
        text-align: center;
    }

    .list-group-flush{
		margin: 5px auto;
        padding:10px;
    }

</style>

<div class="center-column">
    <div class="box">
        <div class = "menu">
            <a class="btn btn-info" href="{% url 'psa:add_patient' %}">Lägg till ny patient</a>
            </br>
            <a class="btn btn-info" href="{% url 'psa:add_provsvar' %}">Lägg till nytt provsvar</a> 
        </div>
        <div class="row-sm">
            <div class = list>
                <h3>Provsvar för läkare att hantera</h3>
                {% if hantera_list %}
                    <ul class="list-group list-group-flush">
                    {% for hantera in hantera_list %}
                        <li class="list-group-item"><a href="{% url 'psa:hantera_detail' hantera.pk %}" class="text-dark">Namn: {{ hantera.name }}</br>Personnumer: {{ hantera.ssn }}</br>Resultat: {{ hantera.result }}</li><br>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>Inga provsvar tillgängliga.</p>
                {% endif %}
            </div>
            </div>
        <div class="row">
            <div class="col-sm">
                <div class = list>
                    <h3>Senast inkomna provsvar</h3>
                    {% if latest_provsvar_list %}
                        <ul class="list-group list-group-flush">
                        {% for provsvar in latest_provsvar_list %}
                            <li class="list-group-item"><a href="{% url 'psa:provsvar_detail' provsvar.id %}" class="text-dark">Skapad: {{ provsvar.created }}</br>Patient: {{ provsvar.ssn }}</br>Resultat: {{ provsvar.result }}</br></a></li><br>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>Inga provsvar tillgängliga.</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm">
            <div class = list>
                <h3>Registrerade patienter</h3>
                {% if patient_list %}
                    <ul class="list-group list-group-flush">
                    {% for patient in patient_list %}
                    <li class="list-group-item"><a href="{% url 'psa:patient_detail' patient.pk %}" class="text-dark">{{ patient.namn }}</a></li><br/>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>Inga patienter tillgängliga.</p>
                {% endif %}
            </div>
            </div>
        </div>
    </div>
</div>

project/psa/templates/psa/patient.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #ffffff;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center-column{
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%, -100%);
	padding: 10px;
	text-align: center;
	width:500px;
	margin: 20px auto;
	padding:20px;
	background-color: rgb(248, 185, 143);
	border-radius: 20px;
	box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

</style>

<div class="center-column">

  {% block content %}
    <h3>Namn: {{ patient.namn }}</h3></br>
	Personnumer: {{ patient.ssn }}</br>
	Gata: {{ patient.gata }}</br>
	Postort: {{ patient.postort }}</br>
	Postnr: {{ patient.postnr }}</br>
	Mail: {{ patient.mail }}</br>
	Operationsdatum: {{ patient.operationsdatum }}</br>
	Skapad: {{ patient.created }}</br>
	Kallelsedatum: {{ patient.kallelsedatum }}

  {% endblock %}

</div>

project/psa/templates/psa/prov.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

<style>

	body{
		background-color: #59a3f1;
	}

	input{
		width: 100%;
		padding: 10px 20px;
		margin: 3px 0;
		box-sizing: border-box;
	}

	.center-column{
		width:500px;
		margin: 20px auto;
		padding:20px;
		background-color: rgb(248, 185, 143);
		border-radius: 20px;
		box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
	}

</style>

<div class="center-column">

  {% block content %}
    <h3>Namn: {{ hantera.name }}</h3>
    Patient: {{ hantera.ssn }}
    Resultat:  {{ hantera.result }}
  {% endblock %}



</div>